//
//  Meal.swift
//  FoundationModelCalorie
//
//  Created by Barış Dilekçi on 28.12.2025.
//

import Foundation
import FoundationModels


/// Represents a meal that the user has eaten.
struct Meal : Identifiable {
    /// Unique identifier for the meal.
    let id = UUID()
    
    /// The name of the food (e.g., "Cheeseburger").
    let name : String
    
    /// Optional nutritional information associated with the meal.
    var calorieInfo : CalorieInfo?
    
}

/// Represents the nutritional information generated by the model.
@Generable
struct CalorieInfo {
    
    @Guide(description: "The estimated calories of the food item")
    var calories : Int
}


